# Generated by Django 5.2.3 on 2025-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_phone_client_phone_number_client_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionnote',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('email', 'Email'), ('call', 'Call'), ('task', 'Task'), ('meeting', 'Meeting'), ('log', 'Log')], default='note', max_length=20),
        ),
    ]
