# Generated by Django 5.2.3 on 2025-06-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_interactionnote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionnote',
            name='type',
            field=models.CharField(choices=[('activity', 'Activity'), ('note', 'Note'), ('email', 'Email'), ('call', 'Call'), ('task', 'Task'), ('meeting', 'Meeting'), ('log', 'Log')], default='note', max_length=20),
        ),
    ]
